// Scopes at key positions of the fixtures: a(file, line, text, scope) means
// every token the line's first `text` covers has `scope` (or a scope under
// it); { nth } picks a later occurrence, { not: true } inverts the check.
const a = (file, line, text, scope, opts = {}) => ({ file, line, text, scope, ...opts });

export const assertions = [
  // Field attributes, after the type and the tag, several per field, on embedded fields.
  a('fields.vuka', 4, 'Base', 'entity.name.type.embedded.vuka'),
  a('fields.vuka', 4, '@', 'punctuation.definition.decorator.vuka'),
  a('fields.vuka', 4, 'orm.Meta', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 4, 'Table', 'variable.other.property.go'),
  a('fields.vuka', 4, '"posts"', 'string.quoted.double'),
  a('fields.vuka', 4, '}}', 'meta.attribute.vuka'),
  a('fields.vuka', 5, 'Timestamps', 'entity.name.type.embedded.vuka'),
  a('fields.vuka', 6, 'ID', 'variable.other.field.vuka'),
  a('fields.vuka', 6, 'int64', 'storage.type'),
  a('fields.vuka', 6, 'orm.PK', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 7, '`json:"title"`', 'string.quoted.raw.vuka'),
  a('fields.vuka', 7, 'orm.Char', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 7, 'Max', 'variable.other.property.go'),
  a('fields.vuka', 7, '200', 'constant.numeric'),
  a('fields.vuka', 7, 'orm.Index', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 8, 'orm', 'entity.name.type.package.go'),
  a('fields.vuka', 8, 'FK', 'entity.name.type.vuka'),
  a('fields.vuka', 8, 'User', 'entity.name.type.vuka'),
  a('fields.vuka', 8, 'orm.Rel', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 9, 'orm.DefaultTo', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 9, '0', 'constant.numeric'),
  a('fields.vuka', 10, 'A', 'variable.other.field.vuka'),
  a('fields.vuka', 10, 'B', 'variable.other.field.vuka'),
  a('fields.vuka', 10, 'X', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 11, 'Option', 'support.type.vuka'),
  a('fields.vuka', 11, 'Time', 'entity.name.type.vuka'),
  a('fields.vuka', 11, '// when', 'comment.line'),
  a('fields.vuka', 13, '}', 'meta.struct.vuka'),
  a('fields.vuka', 15, 'Post', 'meta.struct.vuka', { not: true }),
  a('fields.vuka', 18, 'Title', 'variable.other.field.vuka'),
  a('fields.vuka', 18, 'Pets', 'variable.other.field.vuka'),
  a('fields.vuka', 20, 'db', 'variable.other.field.vuka'),
  a('fields.vuka', 23, 'Embedded', 'entity.name.type.embedded.vuka'),
  a('fields.vuka', 24, '// a comment line', 'comment.line'),
  a('fields.vuka', 25, 'map', 'keyword.type.vuka'),
  a('fields.vuka', 26, 'interface{}', 'keyword.interface.go'),
  a('fields.vuka', 26, 'Doc', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 29, 'X', 'variable.other.field.vuka'),
  a('fields.vuka', 29, 'Min', 'entity.name.function.decorator.vuka'),
  a('fields.vuka', 31, 'Count', 'variable.other.field.vuka'),
  a('fields.vuka', 35, 'X', 'variable.other.field.vuka', { not: true }),

  // Statics, static methods, Self.
  a('statics.vuka', 4, 'Name', 'variable.other.field.vuka'),
  a('statics.vuka', 6, 'static', 'storage.modifier.static.vuka'),
  a('statics.vuka', 6, 'Table', 'variable.other.property.static.vuka'),
  a('statics.vuka', 8, 'const', 'storage.modifier.const.vuka'),
  a('statics.vuka', 8, 'Max', 'variable.other.property.static.vuka'),
  a('statics.vuka', 9, 'Twice', 'variable.other.property.static.vuka'),
  a('statics.vuka', 12, 'User', 'entity.name.type.vuka'),
  a('statics.vuka', 12, 'New', 'entity.name.function.static.vuka'),
  a('statics.vuka', 17, 'Make', 'entity.name.function.static.vuka'),
  a('statics.vuka', 17, 'T', 'entity.name.type.vuka'),
  a('statics.vuka', 19, 'Self', 'variable.language.self.vuka'),
  a('statics.vuka', 20, 'Objects', 'variable.other.property.static.vuka'),

  // Decorators: declarations, before declarations, ?.
  a('decorators.vuka', 3, 'decorator', 'keyword.other.decorator.vuka'),
  a('decorators.vuka', 3, 'logged', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 8, 'retry', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 10, 'Err', 'support.function.vuka', { not: true }),
  a('decorators.vuka', 16, 'retry', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 16, '3', 'constant.numeric'),
  a('decorators.vuka', 17, 'logged', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 18, 'charge', 'entity.name.function.go'),
  a('decorators.vuka', 22, 'web.Get', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 22, '"/pets/{id}"', 'string.quoted.double'),
  a('decorators.vuka', 26, 'orm.Transaction', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 28, '?', 'keyword.operator.try.vuka'),
  a('decorators.vuka', 29, '?', 'keyword.operator.try.vuka'),
  a('decorators.vuka', 30, '?', 'keyword.operator.try.vuka', { not: true }),
  a('decorators.vuka', 34, 'web.Live', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 36, 'Live', 'entity.name.type.embedded.vuka'),
  a('decorators.vuka', 41, 'decorator', 'keyword.other.decorator.vuka'),
  a('decorators.vuka', 41, 'ApiRoute', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 41, '=', 'keyword.operator.composition.vuka'),
  a('decorators.vuka', 41, 'web.Use', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 42, 'Audited', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 44, 'register', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 49, 'Path', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 49, 'id', 'variable.parameter.go', { nth: 2 }),
  a('decorators.vuka', 49, 'Query', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 49, 'Valid', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 49, 'in', 'variable.parameter.go', { nth: 3 }),
  a('decorators.vuka', 53, 'Valid', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 59, 'Path', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 60, 'Body', 'entity.name.function.decorator.vuka'),
  a('decorators.vuka', 60, 'to', 'variable.parameter.go'),

  // match: nested patterns, guards, pins, wildcards.
  a('match.vuka', 4, 'match', 'keyword.control.match.vuka'),
  a('match.vuka', 5, 'case', 'keyword.control'),
  a('match.vuka', 5, 'Ok', 'support.function.vuka'),
  a('match.vuka', 5, 'Some', 'support.function.vuka'),
  a('match.vuka', 5, 'Ok(Some(u))', 'meta.pattern.vuka'),
  a('match.vuka', 7, 'None', 'support.constant.vuka'),
  a('match.vuka', 9, 'NotFound', 'entity.name.type'),
  a('match.vuka', 11, 'if', 'keyword.control.guard.vuka'),
  a('match.vuka', 11, 'errors', 'meta.pattern.vuka'),
  a('match.vuka', 12, 'fmt', 'meta.pattern.vuka', { not: true }),
  a('match.vuka', 18, '^', 'keyword.operator.pin.vuka'),
  a('match.vuka', 19, '_', 'variable.language.wildcard.vuka'),
  a('match.vuka', 21, 'match', 'keyword.control.match.vuka', { not: true }),
  a('match.vuka', 22, 'Some', 'support.function.vuka'),
  a('match.vuka', 23, 'None', 'support.constant.vuka'),

  // JSX.
  a('components.vuka', 3, '<', 'punctuation.definition.tag.begin.jsx.vuka'),
  a('components.vuka', 3, 'h1', 'entity.name.tag.vuka'),
  a('components.vuka', 3, 'Pets', 'string.unquoted.jsx.text.vuka'),
  a('components.vuka', 7, 'len', 'meta.embedded.expression.vuka'),
  a('components.vuka', 8, '{/* a comment */}', 'comment.block.jsx.vuka'),
  a('components.vuka', 10, 'for', 'keyword.control.vuka'),
  a('components.vuka', 10, 'range', 'keyword.control.go'),
  a('components.vuka', 11, 'PetRow', 'entity.name.type.component.vuka'),
  a('components.vuka', 11, 'pet', 'entity.other.attribute-name.jsx.vuka'),
  a('components.vuka', 11, 'key', 'variable.language.key.jsx.vuka'),
  a('components.vuka', 14, 'if', 'keyword.control.vuka'),
  a('components.vuka', 14, 'onClick', 'entity.name.function.event.jsx.vuka'),
  a('components.vuka', 14, 'hx-get', 'entity.other.attribute-name.jsx.vuka'),
  a('components.vuka', 14, 'disabled', 'entity.other.attribute-name.jsx.vuka'),
  a('components.vuka', 14, '&amp;', 'constant.character.entity.jsx.vuka'),
  a('components.vuka', 15, 'theme', 'entity.name.type.package.go'),
  a('components.vuka', 15, 'Card', 'entity.name.type.component.vuka'),
  a('components.vuka', 15, 'List', 'entity.name.type.component.vuka'),
  a('components.vuka', 15, 'User', 'entity.name.type.vuka'),
  a('components.vuka', 15, 'items', 'entity.other.attribute-name.jsx.vuka'),
  a('components.vuka', 15, 'Card', 'entity.name.type.component.vuka', { nth: 2 }),
  a('components.vuka', 16, 'fragment', 'string.unquoted.jsx.text.vuka'),
  a('components.vuka', 23, 'if', 'keyword.control.vuka'),
  a('components.vuka', 23, 'it', 'variable.other'),
  a('components.vuka', 24, 'li', 'entity.name.tag.vuka'),
  a('components.vuka', 25, 'else', 'keyword.control.vuka'),
  a('components.vuka', 25, 'if', 'keyword.control.vuka'),
  a('components.vuka', 27, 'else', 'keyword.control.vuka'),
  a('components.vuka', 30, 'for', 'keyword.control.vuka'),
  a('components.vuka', 30, 'i', 'entity.name.tag.vuka', { nth: 3 }),
  a('components.vuka', 31, 'match', 'keyword.control.match.vuka'),
  a('components.vuka', 32, 'case', 'keyword.control.vuka'),
  a('components.vuka', 32, 'Some', 'support.function.vuka'),
  a('components.vuka', 33, 'b', 'entity.name.tag.vuka'),
  a('components.vuka', 34, 'None', 'support.constant.vuka'),
  a('components.vuka', 35, 'unassigned', 'string.unquoted.jsx.text.vuka'),
  a('components.vuka', 38, 'match', 'keyword.control.match.vuka'),
  a('components.vuka', 39, 'Ok', 'support.function.vuka'),
  a('components.vuka', 44, 'if you like', 'string.unquoted.jsx.text.vuka'),
  a('components.vuka', 46, '}', 'meta.tag.jsx.vuka', { not: true }),
  a('components.vuka', 49, 'onClick', 'entity.name.function.event.jsx.vuka'),
  a('components.vuka', 49, 'onKeyDown', 'entity.name.function.event.jsx.vuka'),
  a('components.vuka', 49, 'func', 'keyword.function.go'),
  a('components.vuka', 49, '+', 'string.unquoted.jsx.text.vuka'),
  a('components.vuka', 53, 'Counter', 'entity.name.type.component.vuka'),
  a('components.vuka', 53, 'Start', 'entity.other.attribute-name.jsx.vuka'),
  a('components.vuka', 57, '<', 'keyword.operator.comparison.go'),
  a('components.vuka', 57, '>', 'keyword.operator.comparison.go'),
  a('components.vuka', 61, '<-', 'keyword.operator.channel.go'),
  // The benchmark page: every token of a table typed from scratch.
  a('benchmark.vuka', 9, 'PetTable', 'entity.name.function.go'),
  a('benchmark.vuka', 9, 'Pet', 'entity.name.type.go', { nth: 2 }),
  a('benchmark.vuka', 10, '<', 'punctuation.definition.tag.begin.jsx.vuka'),
  a('benchmark.vuka', 10, '>', 'punctuation.definition.tag.end.jsx.vuka'),
  a('benchmark.vuka', 11, 'h1', 'entity.name.tag.vuka'),
  a('benchmark.vuka', 11, 'Pets (', 'string.unquoted.jsx.text.vuka'),
  a('benchmark.vuka', 11, '{', 'punctuation.section.embedded.begin.jsx.vuka'),
  a('benchmark.vuka', 11, 'len', 'entity.name.function.support.builtin.go'),
  a('benchmark.vuka', 11, 'pets', 'meta.embedded.expression.vuka'),
  a('benchmark.vuka', 11, '}', 'punctuation.section.embedded.end.jsx.vuka'),
  a('benchmark.vuka', 11, ')', 'string.unquoted.jsx.text.vuka', { nth: 2 }),
  a('benchmark.vuka', 11, '</', 'punctuation.definition.tag.begin.jsx.vuka'),
  a('benchmark.vuka', 12, 'table', 'entity.name.tag.vuka'),
  a('benchmark.vuka', 13, 'th', 'entity.name.tag.vuka', { nth: 6 }),
  a('benchmark.vuka', 13, 'Kind', 'string.unquoted.jsx.text.vuka'),
  a('benchmark.vuka', 14, '{', 'punctuation.section.embedded.begin.jsx.vuka'),
  a('benchmark.vuka', 14, 'for', 'keyword.control.vuka'),
  a('benchmark.vuka', 14, 'range', 'keyword.control.go'),
  a('benchmark.vuka', 14, 'pets', 'variable.other.go'),
  a('benchmark.vuka', 14, '{', 'punctuation.section.block.begin.jsx.vuka', { nth: 2 }),
  a('benchmark.vuka', 15, 'tr', 'entity.name.tag.vuka'),
  a('benchmark.vuka', 17, 'a', 'entity.name.tag.vuka'),
  a('benchmark.vuka', 17, 'href', 'entity.other.attribute-name.jsx.vuka'),
  a('benchmark.vuka', 17, '=', 'punctuation.separator.key-value.jsx.vuka'),
  a('benchmark.vuka', 17, 'Sprintf', 'entity.name.function.support.go'),
  a('benchmark.vuka', 17, '"/pets/%d"', 'string.quoted.double.vuka'),
  a('benchmark.vuka', 17, 'ID', 'meta.embedded.expression.vuka'),
  a('benchmark.vuka', 17, 'Name', 'meta.embedded.expression.vuka'),
  a('benchmark.vuka', 17, 'Name', 'string.unquoted.jsx.text.vuka', { not: true }),
  a('benchmark.vuka', 17, '</', 'punctuation.definition.tag.begin.jsx.vuka'),
  a('benchmark.vuka', 19, 'Kind', 'meta.embedded.expression.vuka'),
  a('benchmark.vuka', 22, '}', 'punctuation.section.block.end.jsx.vuka'),
  a('benchmark.vuka', 22, '}', 'punctuation.section.embedded.end.jsx.vuka', { nth: 2 }),
  a('benchmark.vuka', 24, '</', 'punctuation.definition.tag.begin.jsx.vuka'),
  a('benchmark.vuka', 25, '}', 'punctuation.definition.end.bracket.curly.go'),
];
