// Code generated by vuka from demo.vuka. DO NOT EDIT.

//line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:1:1
// Package demo is stateful components compiled by the Vuka compiler, for
// the live package's property tests and benchmarks. demo_vuka.go is
// generated: go run ./cmd/vuka gen -inplace ./live/internal/demo
package demo; import vuka "github.com/vuka-lang/vuka"

import (
	"context"
	"strconv"
)

// Row is a table row whose state is an Assign: a session renders it again
// only when its quantity or its props change.
type Row struct {
	vuka.Live
	ID   int
	Name string
	qty  vuka.Assign[int]
}

func (r *Row) Inc() { r.qty.Update(func(n int) int { return n + 1 }) }

func (r *Row) Render() vuka.Node {
	return vuka.F(0x4500888e5ca7f1a2, "Ed(E(h)E(h)E(Ed(t)))", vuka.El("tr", []vuka.Attr{{Name: "key", Value: /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:23:18*/r.ID}, }, vuka.El("td", nil, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:23:29*/r.Name), ), vuka.El("td", nil, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:23:46*/r.qty.Get()), ), vuka.El("td", nil, vuka.El("button", []vuka.Attr{{Name: "onClick", Value: vuka.On(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:23:84*/r.Inc)}, }, vuka.Text("+"), ), ), ), )
}

// PlainRow is Row with plain state: rendered again with its table.
type PlainRow struct {
	vuka.Live
	ID   int
	Name string
	qty  int
}

func (r *PlainRow) Inc() { r.qty++ }

func (r *PlainRow) Render() vuka.Node {
	return vuka.F(0x4500888e5ca7f1a2, "Ed(E(h)E(h)E(Ed(t)))", vuka.El("tr", []vuka.Attr{{Name: "key", Value: /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:37:18*/r.ID}, }, vuka.El("td", nil, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:37:29*/r.Name), ), vuka.El("td", nil, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:37:46*/r.qty), ), vuka.El("td", nil, vuka.El("button", []vuka.Attr{{Name: "onClick", Value: vuka.On(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:37:78*/r.Inc)}, }, vuka.Text("+"), ), ), ), )
}

// Table is a table of n rows, each a component.
type Table struct {
	vuka.Live
	N     int
	Plain bool
	title vuka.Assign[string]
}

func (t *Table) Render() vuka.Node {
	return vuka.F(0x1001ea6d61c2e18f, "E(E(h)b)", vuka.El("table", nil, vuka.El("caption", nil, vuka.Child(
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:50:13*/t.title.Get()), ), vuka.Nodes(func(__add func(vuka.Node)) { 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:51:4*/for i := range t.N { __add(vuka.F(0xaf63df4c8601f1a5, "b", vuka.Nodes(func(__add func(vuka.Node)) { 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:5*/if t.Plain { __add(vuka.F(0xaf63de4c8601eff2, "c", func(__a1 int, __a2 int, __a3 string) vuka.Node { return vuka.Component("demo.vuka#1", __a1, &/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:19*/PlainRow{ID: __a2, Name: __a3, }) }(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:33*/i, /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:40*/i, /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:49*/"row " + strconv.Itoa(i), ), )); } /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:80*/else { __add(vuka.F(0xaf63de4c8601eff2, "c", func(__a1 int, __a2 int, __a3 string) vuka.Node { return vuka.Component("demo.vuka#2", __a1, &/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:88*/Row{ID: __a2, Name: __a3, }) }(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:97*/i, /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:104*/i, /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:52:113*/"row " + strconv.Itoa(i), ), )); } }), )); } }), ), 

)
}

// CellTable is a 1000-row table rendered by one component, one cell
// changing per event.
type CellTable struct {
	vuka.Live
	N     int
	cells []int
}

func (t *CellTable) Mount() { t.cells = make([]int, t.N) }

func (t *CellTable) Bump(i int) { t.cells[i]++ }

func (t *CellTable) Render() vuka.Node {
	return vuka.F(0xd5334c12df227221, "E(b)", vuka.El("table", nil, vuka.Nodes(func(__add func(vuka.Node)) { 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:71:4*/for i, v := range t.cells { __add(vuka.F(0x7e145e55294a2476, "Ed(E(th)Es(h)E(Ed(t)))", vuka.El("tr", []vuka.Attr{{Name: "key", Value: 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:72:13*/i}, }, vuka.El("td", nil, vuka.Text("row "), vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:72:25*/i), ), vuka.El("td", []vuka.Attr{{Name: "className", Value: "n"}, }, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:72:51*/v), ), vuka.El("td", nil, vuka.El("button", []vuka.Attr{{Name: "onClick", Value: vuka.On(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:72:79*/func() { t.Bump(i) })}, }, vuka.Text("+"), ), ), ), )); } }), ), 

)
}

// Counter is a counter.
type Counter struct {
	vuka.Live
	Label string
	n     vuka.Assign[int]
}

func (c *Counter) Inc() { c.n.Update(func(n int) int { return n + 1 }) }

func (c *Counter) Render() vuka.Node {
	return vuka.F(0x255446f1e1e9ccd2, "E(hthtEd(t))", vuka.El("span", nil, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:87:16*/c.Label), vuka.Text(": "), vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:87:27*/c.n.Get()), vuka.Text(" "), vuka.El("button", []vuka.Attr{{Name: "onClick", Value: vuka.On(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:87:55*/c.Inc)}, }, vuka.Text("+"), ), ), )
}

// Counters is a page of n counters.
func Counters(n int) func(context.Context) vuka.Node {
	return func(context.Context) vuka.Node {
		return vuka.F(0x77d309cba315688a, "E(b)", vuka.El("main", nil, vuka.Nodes(func(__add func(vuka.Node)) { /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:93:17*/for i := range n { __add(vuka.F(0xaf63de4c8601eff2, "c", func(__a1 int, __a2 string) vuka.Node { return vuka.Component("demo.vuka#3", __a1, &/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:93:37*/Counter{Label: __a2, }) }(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:93:50*/i, /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:93:60*/"c" + strconv.Itoa(i), ), )); } }), ), )
	}
}

type item struct {
	ID   int
	Name string
}

// Board exercises everything a tree holds: keyed and unkeyed loops changed
// by insertions, removals and moves, if and match branches, nested
// components, an opaque node, a script, children.
type Board struct {
	vuka.Live
	Title    string
	Children vuka.Node
	items    []item
	next     int
	mode     string
	note     string
	open     bool
}

func (b *Board) Mount() {
	for _, n := range []string{"milk", "eggs", "tea"} {
		b.add(n)
	}
}

func (b *Board) add(name string) {
	b.next++
	b.items = append(b.items, item{b.next, name})
}

// Do edits the list as its word says.
func (b *Board) Do(w string) {
	n := len(b.items)
	switch {
	case w == "add":
		b.add("new" + strconv.Itoa(b.next))
	case w == "front":
		b.next++
		b.items = append([]item{{b.next, "front"}}, b.items...)
	case w == "drop" && n > 0:
		b.items = b.items[1:]
	case w == "pop" && n > 0:
		b.items = b.items[:n-1]
	case w == "rotate" && n > 1:
		b.items = append(b.items[1:], b.items[0])
	case w == "reverse":
		for i, j := 0, n-1; i < j; i, j = i+1, j-1 {
			b.items[i], b.items[j] = b.items[j], b.items[i]
		}
	case w == "swap" && n > 2:
		b.items[0], b.items[n-1] = b.items[n-1], b.items[0]
	case w == "rename" && n > 0:
		b.items[n/2].Name += "!"
	case w == "mid" && n > 1:
		it := b.items[0]
		rest := append([]item{}, b.items[1:]...)
		b.items = append(append(rest[:len(rest)/2:len(rest)/2], it), rest[len(rest)/2:]...)
	case w == "clear":
		b.items = nil
	default:
		b.mode = w
	}
}

func (b *Board) Toggle() { b.open = !b.open }

func (b *Board) Note(s string) { b.note = s }

func (b *Board) Remove(id int) {
	for i, it := range b.items {
		if it.ID == id {
			b.items = append(b.items[:i:i], b.items[i+1:]...)
			return
		}
	}
}

func (b *Board) Render() vuka.Node {
	return vuka.F(0x208d9ada60bb505f, "Ed(Ed(htht)hEdd()Ed(t)E(b)E(b)bbE(h)b)", vuka.El("section", []vuka.Attr{{Name: "className", Value: /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:175:29*/"board " + b.mode}, }, vuka.El("h2", []vuka.Attr{{Name: "title", Value: 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:176:14*/b.note}, }, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:176:23*/b.Title), vuka.Text(" ("), vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:176:34*/len(b.items)), vuka.Text(")"), ), vuka.Child(
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:177:4*/b.Children), vuka.El("input", []vuka.Attr{{Name: "onInput", Value: vuka.On(
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:178:19*/b.Do)}, {Name: "value", Value: /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:178:32*/b.mode}, }, ), vuka.El("button", []vuka.Attr{{Name: "onClick", Value: vuka.On(
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:179:20*/b.Toggle)}, }, vuka.Text("toggle"), ), vuka.El("ul", nil, vuka.Nodes(func(__add func(vuka.Node)) { 

/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:181:5*/for _, it := range b.items { __add(vuka.F(0xbb03a5071d868fe7, "Ed(htcEd(t))", vuka.El("li", []vuka.Attr{{Name: "key", Value: 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:182:14*/it.ID}, }, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:182:22*/it.Name), vuka.Text(" "), vuka.Component("demo.vuka#4", nil, &/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:182:32*/Counter{Label: it.Name, }), vuka.El("button", []vuka.Attr{{Name: "onClick", Value: vuka.On(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:182:75*/func() { b.Remove(it.ID) })}, }, vuka.Text("x"), ), ), )); } }), ), vuka.El("ol", nil, vuka.Nodes(func(__add func(vuka.Node)) { 


/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:185:8*/for i, it := range b.items { __add(vuka.F(0x58e327489fab1530, "E(hth)", vuka.El("li", nil, vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:185:42*/i), vuka.Text(": "), vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:185:47*/it.Name), ), )); } }), ), vuka.Nodes(func(__add func(vuka.Node)) { 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:186:4*/if b.open { __add(vuka.F(0x433c8382836d2b7d, "Ed(th)", vuka.El("p", []vuka.Attr{{Name: "onClick", Value: vuka.On(
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:187:16*/b.Toggle)}, }, vuka.Text("open "), vuka.Child(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:187:32*/b.note), ), )); 
} /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:188:5*/else if len(b.items) == 0 { __add(vuka.F(0xf674339c770eef02, "E(t)", vuka.El("p", nil, vuka.Text("empty"), ), )); 

} /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:190:5*/else { __add(vuka.F(0xc1566abc726ea497, "E(t)", vuka.El("p", nil, vuka.Text("closed"), ), )); } }), vuka.Nodes(func(__add func(vuka.Node)) { 


/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:193:4*/if __m1 := /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:193:10*/b.mode; false { panic(__m1)
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:194:3*/} else if __m1 == "big" { __add(vuka.F(0xfe27e6131077520f, "E(t)", vuka.El("b", nil, vuka.Text("BIG"), ), )); 

/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:196:3*/} else if __m1 == "note" { __add(vuka.F(0x9eeb9795ae044d61, "Edd()", vuka.El("input", []vuka.Attr{{Name: "onInput", Value: vuka.On(
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:197:20*/b.Note)}, {Name: "value", Value: /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:197:35*/b.note}, }, ), )); 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:198:3*/} else if true { __add(vuka.F(0xaf63e54c8601fbd7, "h", vuka.Child(
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:199:5*/vuka.El("i", nil, vuka.Text("opaque " + b.mode), vuka.Component("demo#opaque", nil, &Counter{Label: "inner"}))), )); 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:200:3*/} else { panic("vuka: no case matched") }/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:200:4*/ }), vuka.El("script", nil, vuka.Child(
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:201:12*/"var mode = '" + b.mode + "' </script>"), ), vuka.Nodes(func(__add func(vuka.Node)) { 
/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:202:4*/for _, it := range b.items { __add(vuka.F(0xaf63de4c8601eff2, "c", func(__a1 int, __a2 string) vuka.Node { return vuka.Component("demo.vuka#5", __a1, 
&/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:203:5*/Counter{Label: __a2, }) }(/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:203:18*/it.ID, /*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:203:32*/"k" + it.Name, ), )); } }), ), 

)
}

// Page is a page with two boards and a counter.
func Page(context.Context) vuka.Node {
	return vuka.F(0x8ead5c5cbb04d351, "E(ccc)", vuka.El("main", nil, vuka.Component("demo.vuka#6", nil, 
&/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:211:4*/Board{Title: "one", Children: vuka.F(0x86ef4689d48dafbf, "E(t)", vuka.El("em", nil, vuka.Text("first"), ), ), }), vuka.Component("demo.vuka#7", nil, 
&/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:212:4*/Board{Title: "two", }), vuka.Component("demo.vuka#8", nil, 
&/*line /Users/amtz/Documents/personal/vuka-wt-live-diff/live/internal/demo/demo.vuka:213:4*/Counter{Label: "solo", }), ), 
)
}

// Words are the values RandomEvent sends: Board.Do's commands and more.
var Words = []string{"add", "front", "drop", "pop", "rotate", "reverse", "swap", "rename", "mid", "clear", "big", "note", "x", "<b>&\"", "add", "rotate", "a much longer note, long enough to be kept by reference on the connection......"}
