package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// module writes a module using the local runtime and returns its directory.
func module(t *testing.T, files map[string]string) string {
	t.Helper()
	repo, _ := filepath.Abs("../..")
	dir := t.TempDir()
	files["go.mod"] = "module m\n\ngo 1.22\n\nrequire github.com/vuka-lang/vuka v0.3.0\n\nreplace github.com/vuka-lang/vuka => " + repo + "\n"
	for name, src := range files {
		path := filepath.Join(dir, name)
		os.MkdirAll(filepath.Dir(path), 0o755)
		if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	t.Setenv("GOWORK", "off")
	return dir
}

func chdir(t *testing.T, dir string) {
	t.Helper()
	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.Chdir(old) })
}

const staticsSrc = `package main

import "fmt"

type User struct {
	Name string

	static Table = "users"
	static count int
}

func User.New(name string) *User { User.count++; return &User{Name: name} }

func main() {
	u := User_New("ada") // "User_Table" in a string stays
	fmt.Println(u.Name, User_Table, _User_count)
}
`

func TestFix(t *testing.T) {
	dir := module(t, map[string]string{
		"main.vuka":    staticsSrc,
		"gone_vuka.go": "// Code generated by vuka from gone.vuka. DO NOT EDIT.\n\npackage main\n",
		"kept_vuka.go": "// written by hand\n\npackage main\n",
	})
	chdir(t, dir)

	var out bytes.Buffer
	if err := fix([]string{"-n"}, &out); err != nil {
		t.Fatal(err)
	}
	if src, _ := os.ReadFile("main.vuka"); string(src) != staticsSrc {
		t.Fatal("-n changed main.vuka")
	}
	if !strings.Contains(out.String(), "not applied") {
		t.Fatalf("-n output: %s", out.String())
	}

	out.Reset()
	if err := fix(nil, &out); err != nil {
		t.Fatal(err)
	}
	src, _ := os.ReadFile("main.vuka")
	for _, want := range []string{`u := User.New("ada") // "User_Table" in a string stays`, "fmt.Println(u.Name, User.Table, User.count)"} {
		if !strings.Contains(string(src), want) {
			t.Fatalf("static-names: want %q in\n%s", want, src)
		}
	}
	if fileExists("gone_vuka.go") {
		t.Error("orphans: gone_vuka.go is still there")
	}
	if !fileExists("kept_vuka.go") {
		t.Error("orphans: removed a file vuka didn't write")
	}

	out.Reset()
	if err := fix(nil, &out); err != nil || strings.TrimSpace(out.String()) != "nothing to fix" {
		t.Fatalf("second run: %v %s", err, out.String())
	}
}

func TestCompareVersions(t *testing.T) {
	for _, c := range []struct {
		a, b string
		want int
	}{
		{"v0.2.0", "v0.3.0", -1}, {"v0.3.0", "v0.3.0", 0}, {"v1.0.0", "v0.9.9", 1},
		{"v0.0.0-20261009181746-ce33f0c4f632", "v0.1.0", -1}, {"v0.3.0-rc1", "v0.3.0", -1},
	} {
		if got := compareVersions(c.a, c.b); got != c.want {
			t.Errorf("compareVersions(%s, %s) = %d, want %d", c.a, c.b, got, c.want)
		}
	}
}

func TestExplain(t *testing.T) {
	dir := module(t, map[string]string{"main.vuka": staticsSrc, "plain.vuka": "package main\n\nfunc plain() {}\n"})
	var out bytes.Buffer
	if err := explain([]string{filepath.Join(dir, "main.vuka")}, &out); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"main.vuka:8\n  vuka │     static Table = \"users\"\n  vuka │     static count int\n  go   │ (becomes a comment here; its Go is below)",
		"main.vuka:8  added after the code, for: static Table = \"users\"\n  go   │ var User_Table = \"users\"",
		"main.vuka:12\n  vuka │ func User.New(name string) *User { User.count++; return &User{Name: name} }\n" +
			"  go   │ func User_New(name string) *User { _User_count++; return &User{Name: name} }",
	} {
		if !strings.Contains(out.String(), want) {
			t.Fatalf("explain: want\n%s\nin\n%s", want, out.String())
		}
	}
	out.Reset()
	if err := explain([]string{filepath.Join(dir, "plain.vuka")}, &out); err != nil || !strings.Contains(out.String(), "plain Go") {
		t.Fatalf("plain file: %v %s", err, out.String())
	}
}
