package load

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/vuka-lang/vuka/transpile"
)

// Marker is the file that marks a directory as Mirror's output, so it never
// syncs over (and deletes the files of) a directory it didn't make.
const Marker = ".vuka-build"

const markerText = "This directory is generated by vuka from the module above it. Don't edit it; run vuka gen.\n"

// MirrorResult says what Mirror changed.
type MirrorResult struct {
	Written, Removed []string // paths relative to the output module
}

// Mirror makes out a complete Go module that plain Go tools build: the module at
// root with every .vuka file replaced by its generated Go and everything else
// copied (go.mod with relative replace paths adjusted, .go files, assets,
// testdata). Only files that differ are written, and files no longer in the
// source are removed. With dryRun nothing is touched; the result lists what
// would change.
func Mirror(root, out string, gens []Generated, dryRun bool) (MirrorResult, error) {
	var res MirrorResult
	root, _ = filepath.Abs(root)
	out, _ = filepath.Abs(out)
	if entries, err := os.ReadDir(out); err == nil && len(entries) > 0 {
		if _, err := os.Stat(filepath.Join(out, Marker)); err != nil {
			return res, fmt.Errorf("%s exists and wasn't made by vuka; choose another output directory", out)
		}
	}
	want := map[string][]byte{Marker: []byte(markerText)} // relative path → content
	modes := map[string]fs.FileMode{}

	generated := map[string]bool{}
	for _, g := range gens {
		rel, err := filepath.Rel(root, g.Target)
		if err != nil {
			return res, err
		}
		want[rel] = g.Src
		generated[rel] = true
	}
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, path)
		name := d.Name()
		if d.IsDir() {
			switch {
			case path == root:
				return nil
			case path == out,
				strings.HasPrefix(name, "."), strings.HasPrefix(name, "_"), name == "node_modules":
				return filepath.SkipDir
			}
			if _, err := os.Stat(filepath.Join(path, "go.mod")); err == nil {
				return filepath.SkipDir // a nested module isn't part of this one
			}
			return nil
		}
		if !d.Type().IsRegular() || strings.HasSuffix(name, ".vuka") || generated[rel] ||
			name == "go.work" || name == "go.work.sum" || strings.HasPrefix(name, ".") {
			return nil
		}
		if siblingVuka(path) {
			return nil // an in-place generated file; the fresh one replaces it
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if rel == "go.mod" {
			data = relocateReplaces(data, root, out)
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		want[rel] = data
		modes[rel] = info.Mode().Perm()
		return nil
	})
	if err != nil {
		return res, err
	}

	// go.mod first: once out has one, it is a separate module that
	// Discover and the root module's ./... leave alone.
	rels := make([]string, 0, len(want))
	for rel := range want {
		rels = append(rels, rel)
	}
	sort.Slice(rels, func(i, j int) bool { return rels[i] == "go.mod" || rels[j] != "go.mod" && rels[i] < rels[j] })
	for _, rel := range rels {
		dst := filepath.Join(out, rel)
		if old, err := os.ReadFile(dst); err == nil && bytes.Equal(old, want[rel]) {
			continue
		}
		res.Written = append(res.Written, rel)
		if dryRun {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return res, err
		}
		mode := modes[rel]
		if mode == 0 {
			mode = 0o644
		}
		if err := os.WriteFile(dst, want[rel], mode); err != nil {
			return res, err
		}
	}

	var dirs []string
	err = filepath.WalkDir(out, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) {
				return filepath.SkipAll
			}
			return err
		}
		rel, _ := filepath.Rel(out, path)
		if d.IsDir() {
			if path != out {
				dirs = append(dirs, path)
			}
			return nil
		}
		if _, ok := want[rel]; !ok {
			res.Removed = append(res.Removed, rel)
			if !dryRun {
				return os.Remove(path)
			}
		}
		return nil
	})
	if err != nil {
		return res, err
	}
	if !dryRun {
		for i := len(dirs) - 1; i >= 0; i-- {
			_ = os.Remove(dirs[i]) // only succeeds when empty
		}
	}
	return res, nil
}

// siblingVuka reports whether path is the generated file of a .vuka file
// beside it.
func siblingVuka(path string) bool {
	dir, name := filepath.Split(path)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".vuka") && transpile.GoName(e.Name()) == name {
			return true
		}
	}
	return false
}

var replacePath = regexp.MustCompile(`(=>\s*)(\.\.?/[^\s]*|\.\.?)(\s|$)`)

// relocateReplaces rewrites go.mod's relative replace paths so they still
// point at the same directories from out.
func relocateReplaces(mod []byte, root, out string) []byte {
	return replacePath.ReplaceAllFunc(mod, func(m []byte) []byte {
		g := replacePath.FindSubmatch(m)
		target := filepath.Join(root, filepath.FromSlash(string(g[2])))
		rel, err := filepath.Rel(out, target)
		if err != nil {
			return m
		}
		rel = filepath.ToSlash(rel)
		if !strings.HasPrefix(rel, ".") {
			rel = "./" + rel
		}
		return append(append(append([]byte{}, g[1]...), rel...), g[3]...)
	})
}
